### ISSUE TITLE
Feature: 메인 페이지의 배너, 네일아트 카드 리스트를 사용자가 확인할 수 있다. (UI 작업)

### ISSUE THREAD

**Issue by pexe99** [team-JaPyGuri/JaPyGuri-FE#13]
## Feature Description
Home page 기본 UI 구성

## To-Do
- [x] Banner component 개발
- [x] HotNailList component 개발
- [x] nailList.json mock 데이터 추가
- [x] nailList.json mock 데이터 적용
- [x] HotNailList onClick event에 BottomUpSheet 추가
- [x] NailDetail component 추가
- [x] NailSnap component 추가
- [x] Layout component 일부 수정
- [x] NavigationBar component 일부 수정

### 추가 사항
