### ISSUE TITLE
Feature: 사용자는 현재 위치를 기반으로 지도를 확인할 수 있으며, 네일샵 핀을 확인할 수 있다.

### ISSUE THREAD

**Issue by pexe99** [team-JaPyGuri/JaPyGuri-FE#15]
## Feature Description
요청 페이지 Map 기본 작업

## To-Do
- [x] Naver Map API key 발급
- [x] Naver Map API 기본 설정
- [x] Request Map page에서 Layout component 사용을 위한 수정
- [x] Header, Footer, NavigationBar component를 Layout에서 분리
- [x] event 전파를 막기 위한 stopPropagation.tsx util 추가
- [x] state 변경에 대한 component 상태 변화 반영을 위해 NailDetail.tsx에 local state 추가
- [x] url 변화에 따른 BottomUpSheet 닫음 처리를 위한 BottomUpSheetContainer 수정
- [x] ToastContainer와 BottomUpSheetContainer 사용 위치 변경
- [x] drag event를 통한 지도 중앙 좌표 변경 state 반영
- [x] 좌표값을 바탕으로 reverseGeocording 적용
- [x] 주소 확인을 위한 MapFooter component 추가
- [x] 화면 위치 이동에 따른 Marker 동적 랜더링 적용
- [x] Marker 랜더링 여부에 따른 activeMarkerCounter state 추가

### 추가 사항
