### ISSUE TITLE
Feature: 스크롤함에 따라 서버로부터 받아온 추가 네일아트 카드를 확인할 수 있다.

### ISSUE THREAD

**Issue by pexe99** [team-JaPyGuri/JaPyGuri-FE#17]
## Feature Description
Main page 서버 연동 작업

## To-Do
- [x] Back-end 관련 API 확인, env 파일 수정
- [x] HotNail API 연동
- [x] NailSnap API 연동
- [x] Intersection Observer를 활용한 Infinity Scroll 구현

### 추가 사항
