### ISSUE TITLE
Feature: 사용자가 좋아요 표시한 네일아트 카드를 서버로부터 전달받아 리스트 형태로 확인할 수 있다.

### ISSUE THREAD

**Issue by pexe99** [team-JaPyGuri/JaPyGuri-FE#18]
## Feature Description
사용자 좋아요 페이지 작업

## To-Do
- [x] netlify 환경에서 배포 시, redirect를 위한 netlify.toml 추가
- [x] Main page Back-end API 연동
- [x] Intersection observer를 활용한 Infinity scroll 구현
- [x] toggleLike 기능 구현
- [x] ShopList api 적용
- [x] RequestMap page에서 핀 로드
- [x] 핀 click event 추가
- [x] click에 따른 네일샵 정보 노출
- [x] NavigationBar component 수정
- [x] NoContents component 추가
- [x] ToastContainer 위치 수정
- [x] SelectNail 페이지 UI 작업
- [x] RequestResult 페이지 UI 작업
- [x] AiRequest 페이지 UI 작업

### 추가 사항
