### ISSUE TITLE
Feature: eslint와 prettier 설정을 완료한다.

### ISSUE THREAD

**Issue by pexe99** [team-JaPyGuri/JaPyGuri-FE#3]
## Feature Description
프로젝트 전반 formatting을 위한 esline와 prettier 설정
SPA routing을 위한 react router dom 설치 및 적용
상태 관리를 위한 Recoil 설치 및 적용

## To-Do
- [x] prettier 설치
- [x] prettier 적용 여부 확인
- [x] react router dom 설치
- [x] react router dom 적용 여부 확인
- [x] recoil 설치
- [x] recoil 적용 여부 확인

### 추가 사항
